name: "build"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "install dfx"
      run: |
        wget -O install-dfx.sh https://sdk.dfinity.org/install.sh
        yes Y | DFX_VERSION=0.6.26 bash install-dfx.sh
        echo "/home/runner/bin" >> $GITHUB_PATH
    - name: "install dfx cache"
      run: dfx cache install
    - name: "install vessel"
      run: |
        wget -O /home/runner/bin/vessel https://github.com/kritzcreek/vessel/releases/download/v0.6.0/vessel-linux64
        chmod +x /home/runner/bin/vessel
    - name: "run"
      run: ./run.sh
